### ISSUE TITLE
Base repo setup

### ISSUE THREAD

**Issue by KN408** [Team-GMKK/meal-evolution#3]

**Comment by KN408** [comment]
1A. Install node & watchman. (Pretty sure we all have those already but just in case)
1B. Install xcode
2. You will also need to install the Xcode Command Line Tools. Open Xcode, then choose “Preferences...” from the Xcode menu. Go to the Locations panel and install the tools by selecting the most recent version in the Command Line Tools dropdown
3. Install cocoapods with "sudo gem install cocoapods"
4. Pull the repo & run "npm install"
5. Inside the repo directory, to start the app, run "npx react-native run-ios"

Simulator should begin running and a new terminal window with a "Metro Bundler" will open. This is your console for the app.

**Comment by gabsong** [comment]
@KN408 can you include any links / commands to run?

**Comment by KN408** [comment]
Link to the official documentation for setting up if you want. 
https://reactnative.dev/docs/environment-setup
